name: 'say-hello'
description: 'Returns a greeting output with a greeting to the input name'
runs:
  using: "composite"
  steps:
    - name: say-hello
      shell: bash
      run: |
        echo "hello there"
