name: Greetings
# on: [workflow_dispatch]
on:
  push:
    branches:
      - test
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Call Composite Action say-hello
      uses: ./actions

    - name: echo output from say-hello
      run: |
        echo "done test environment"
